package Lang_IVR.sandbox;

/*Generated by MPS */

import java.awt.event.ActionListener;
import JAVA.IVR.runtime.runtime.Event;
import java.util.ArrayList;
import JAVA.IVR.runtime.runtime.Variables;
import JAVA.IVR.runtime.runtime.Behaviour;
import JAVA.IVR.runtime.runtime.Style;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import JAVA.IVR.runtime.runtime.Data;
import javax.swing.JButton;
import java.awt.Dimension;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import JAVA.IVR.runtime.runtime.MacVoice;
import java.io.IOException;

public class Test_Demo_0 implements ActionListener {


  public static Test_Demo_0 instance;

  public static void initHashMap() {

    Event Home = new Event("Test Demo", "0");
    Home.setAction("", true);
    Home.setPlayBack("Welcome to " + "Test Demo");

    Home.setPlayBack("I");
    Home.childs = new ArrayList<Event>();
    Home.isFinal = false;
    Variables.main_Text = "Test Demo";

    Variables.myHashMap.put("0", Home);





  }

  public static void main(String[] args) {
    initHashMap();
    instance = new Test_Demo_0();
    Test_Demo_0.initHashMap();
    initView();
    Behaviour.runInitSetup();

  }

  public static void initView() {
    Style.setContent();
    addButtons(Style.myPanelOfButtons);
    Style.myPhone.add(Style.myPanelOfButtons, BorderLayout.SOUTH);
    Style.setFrame();
  }

  public static void addButtons(JPanel myPanelOfButtons) {
    for (Data.Status item : Data.Status.values()) {
      JButton button = new JButton(item.getCode());
      button.setActionCommand(item.getCode());
      button.addActionListener(instance);
      button.setPreferredSize(new Dimension(78, 76));
      Border border = new LineBorder(Color.white, 13);
      button.setBorder(border);
      myPanelOfButtons.add(button);
    }
  }
  @Override
  public void actionPerformed(ActionEvent event) {
    if (!(((Variables.path == null || Variables.path.length() == 0) || Variables.finished == true || Variables.started == false))) {
      try {
        if (Variables.timerThr.isAlive()) {
          Variables.timerThr.interrupt();
        }
        try {
          if (MacVoice.waitingThr.isAlive()) {
            MacVoice.waitingThr.interrupt();
          }
        } catch (Exception e) {
        }
        Behaviour.runLogic(event, false);

      } catch (IOException e) {
        e.printStackTrace();
      }


    }
  }

}
